# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Michael Halfmoon
email: michael-halfmoon@utulsa.edu
description: > # this means to ignore newlines until "baseurl:"
  The personal site of a plasma physicist and webdev hobbyist Michael Halfmoon.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mhalfmoon.github.io/" # the base hostname & protocol for your site
twitter_username: mhalfmoon
github_username:  mhalfmoon

# Build settings
markdown: kramdown
